version: '3'
services:
  app:
    build: app
    ports:
      - '3000:80'
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo:
